user_number = int(input("Wprowadź wartośc: "))
print("Uzytkownik wprowadzil", user_number)
user_number1 = int(input("Wprowadź wartośc: "))
print("Uzytkownik wprowadzil", user_number1)
user_number = int(input("Wprowadź wartośc: "))
print("Uzytkownik wprowadzil", user_number)
user_number1 = int(input("Wprowadź wartośc: "))
print("Uzytkownik wprowadzil", user_number1)
print(user_number + user_number1)